apiVersion: apps/v1
kind: Deployment
metadata:
  name: t2seed
  namespace: default
  labels:
    app: t2seed
spec:
  replicas: 10
  selector:
    matchlabels:
      app: t2seed
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: t2seed
    spec:
      containers:
      - image: 4reallive/t2seed:loglevel6
        imagePullPolicy: Always
        name: t2seed
        ports:
        - containerPort: 12897
          name: p2p
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
